### PR TITLE
Apparently w3m is a thing and it is nicer than lynx

### LINKED ISSUE #39: Add w3m adaptor
Because sometimes it's just a bit nicer than lynx

### PR DESCRIPTION
**Pull request by qhoxie**
Fixes #39

### CODE REVIEW

**Comment by qhoxie** [comment]
@dafyddcrosby I wasn't familiar with w3m before this.  Will this work?  Apologies for the delay.

**Comment by dafyddcrosby** [comment]
<3 YOLO <3

**Comment by qhoxie** [comment]
Signed off by @dafyddcrosby

**Comment by look** [comment]
aw yiss

**Pull request merged**
